# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370795c644e519b081995ddd4065a68f0a61d216f5afb89a13a32fe160e7af5d66c4b9f2f54628b3cdbb758ac1cf92c7a363f54362c1d31039f93e7f69ebbcb6

test:
  secret_key_base: e676a41235d0ad242e1b86adfe7a15afe1c659fd2a2d2de111b05ecb40d1b17b873a6d1b05cf22337272afc347541faa87e9d7053b86607731543e1f1088eb1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
